---
title: Traffic Data Analysis
output: html_document
---

this is where things start :)

```{r}
library("dplyr")

bey2ollak <- read.csv('all-semi-unique.csv')
unique(bye2ollak$ad.aid)
filteredColumns <- select(bey2ollak, - c(ad.aid, ad.bgcl, ad.bgcls, ad.fncl, ad.fncls, ad.lid ,ad.logo, ad.logo2x, ad.logoAndroidS , ad.logoAndroidH, ad.cm, ad.url, ad.g, rd.img, rd.cl, rd.rp.rpImg, rd.rp.img, rd.rp.type) )

filteredColumns <- dplyr::distinct(filteredColumns) 

filteredColumns <- dplyr::filter(filteredColumns, !is.na(filteredColumns$rd.stid))

filteredColumns <- dplyr::filter(filteredColumns, !is.na(filteredColumns$rd.hr))

filteredColumns$crawl_date = strptime(as.character(filteredColumns$crawl_date),"%a %b %d %H:%M:%S UTC %Y")
filteredColumns$crawl_date = as.character(filteredColumns$crawl_date)
filteredColumns <- dplyr::filter(filteredColumns, !duplicated(filteredColumns$rd.rp.cmid))
filteredColumns$rd.rp.cm[filteredColumns$rd.rp.stid == 2] <- "lazeez"
filteredColumns$rd.rp.cm[filteredColumns$rd.rp.stid == 3] <- "mashy"
filteredColumns$rd.rp.cm[filteredColumns$rd.rp.stid == 4] <- "za7ma"
filteredColumns$rd.rp.cm[filteredColumns$rd.rp.stid == 5] <- "mafeesh amal"
filteredColumns$rd.rp.cm[filteredColumns$rd.rp.stid == 6] <- "eh el nezam?"
filteredColumns$rd.rp.cm[filteredColumns$rd.rp.stid == 7] -> "khatar"
filteredColumns$rd.rp.cm[filteredColumns$rd.rp.stid == 8] -> "7adsa"
filteredColumns$rd.rp.cm[filteredColumns$rd.rp.stid == 9] -> "3otl"

 
